# title of website
title: Cc导航

# description of website
description: cclss's navigation site

# favicon of website
favicon: "https://github.com/cclss.png?size=40"

# your website url
url: https://www.cclss.top/

# github profile url
github: "https://github.com/cclss"

# footer message
footer: © 2021-2022 @cclss

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-EXE1PJ8CR2"

content:
  categories:
    - name: CTF刷题
      sites:
        - name: BUUCTF
          description: CTF 训练平台,拥有全网数量最庞大的 CTF 题库
          url: https://buuoj.cn/
        - name: 攻防世界
          description: Xctf刷题
          url: https://adworld.xctf.org.cn/
        - name: CTFHUB
          description: 专注网络安全、信息安全、白帽子技术的在线学习
          url: https://www.ctfhub.com/
        - name: NSSCTF
          description: xenny大神良心制作可以复现最近比赛题
          url: https://www.ctfer.vip/
        - name: CTF-TIME
          description: Capture The Flag, CTF teams, CTF ratings, CTF archive, CTF writeups
          url: https://ctftime.org/
        - name: BUGKU
          description: 刷题支持awd
          url: https://ctf.bugku.com/
        - name: CTF-SHOW
          description: 新手入门CTF的好地方
          url: https://ctf.show/
        - name: 墨者学院
          description:  专注于网络安全人才培养
          url: https://www.mozhe.cn/
        - name: Jarvis OJ
          description:   Jarvis OJ is a CTF training platform developed by Jarvis from USSLab in ZJU. 
          url: https://www.jarvisoj.com/
        - name: 白帽子ctf
          description: 普通刷题
          url: http://bmzclub.cn/
        - name: hackme
          description: 国外
          url: https://hack.me/
        - name: DEFCON
          description: The largest hacking and security conference with presentations
          url: https://defcon.org/
        - name: PWNthebox
          description: Hacking Platform - CTF Platform
          url: https://ce.pwnthebox.com/
        - name: Vulfocus
          description: 漏洞复现 
          url: https://vulfocus.cn/
    - name: WIKE
      sites:
        - name: ctfwiki
          description: ctf 各种知识
          url: https://ctf-wiki.org/
        - name: susctf_wiki
          description: 四川大学网络空间wiki
          url: https://www.scuctf.com/
        - name: 狼组文库
          description: 包含渗透以及各种
          url: https://wiki.wgpsec.org/knowledge/
        - name: Docker
          description: Docker-从入门到实践
          url: https://yeasy.gitbook.io/docker_practice/
        - name: 渗透
          description: 属于某个大佬自己完善的知识库
          url: https://blog.gm7.org/
        - name: PHP代码审计入门指南
          description: PHP代码审计入门指南
          url: https://www.yuque.com/burpheart/phpaudit/
        - name: HackTricks
          description: 国际平台 各种知识 还能学英语
          url: https://book.hacktricks.xyz/
        - name: 图解系列
          description: 图解计算机网络、操作系统、计算机组成、数据库，让天下没有难懂的八股文！
          url: https://xiaolincoding.com/
    - name: TOOLS
      sites:
        - name: cyberchef
          description: 解密无敌工具
          url: https://pw.cclss.top/
        - name: CIP
          description: 获取你的ip
          url: http://cip.cc/
        - name: XSS
          description: XSS
          url: https://xss8.cc/login/
        - name:  Explain Shell
          description:  Shell命令解析
          url: https://explainshell.com/
        - name:  Ceye DNS
          description:  DNS oob平台
          url: http://ceye.io/
        - name: DNS log
          description: DNS oob平台
          url: http://dnslog.cn/
        - name: DNSlog Dig.pm
          description: 比dnslog.cn好用
          url: https://dig.pm/
        - name: RequestBin
          description: 获取request请求
          url: https://requestbin.io/
        - name: XSS Chop
          description: XSS Chop
          url: https://xsschop.chaitin.cn/demo/
        - name: CTF在线工具
          description: CTF在线工具
          url: http://www.hiencode.com/
        - name: java命令执行转换
          description: java命令执行转换
          url: https://x.hacking8.com/java-runtime.html
        - name: cmd5
          description: cmd5
          url: https://www.cmd5.com/
        - name: somd5
          description: somd5
          url: https://www.somd5.com/
        - name: china md5
          description: china md5
          url: http://www.chamd5.org/
        - name: jsfuck
          description: jsfuck 解密
          url: http://www.jsfuck.com/
        - name: AES
          description: aes 在线解密
          url: http://aes.online-domain-tools.com/
        - name: jwt
          description: jwt
          url: https://jwt.io/
        - name: unicode
          description: unicode
          url: https://www.compart.com/en/unicode/
        - name: Brainfuck
          description: Brainfuck
          url: http://bf.doleczek.pl/
        - name: 在线php
          description: 好用的在线php
          url: https://tool.lu/coderunner/
        - name: 正则
          description: 在线正则
          url: https://regex101.com/
        - name: unicode-converter
          description: unicode
          url: https://www.branah.com/unicode-converter
        - name: 子域名爆破
          description: 子域名在线爆破
          url: https://phpinfo.me/domain/
        - name: suid提权
          description: suid提权
          url: https://gtfobins.github.io/
        - name: crt
          description: 域名历史解析
          url: https://crt.sh/
        
    - name: 网络空间搜索
      sites:
        - name: shodan
          description: Shodan provides a comprehensive view of all exposed services to help you stay secure
          url: https://www.shodan.io/
        - name: Fofa
          description: FOFA 是白帽汇推出的一款网络空间搜索引擎
          url: https://fofa.info/
        - name: zoomeye
          description: 钟馗之眼
          url: https://www.zoomeye.org/
        - name: 谛听
          description: 谛听
          url: https://www.ditecting.com/
        - name: 360网络空间测绘
          description: 360网络空间测绘
          url: https://quake.360.cn/quake/#/index
    - name: 病毒分析 风险测试
      sites:
        - name: VirusTotal
          description: 提供免费的可疑文件分析服务的网站
          url: https://www.virustotal.com
        - name: 腾讯哈勃
          description: “哈勃分析系统”,是“腾讯反病毒实验室”自主研发的安全辅助平台
          url: https://habo.qq.com/
        - name: VirScan
          description: 多引擎在线病毒扫描网
          url: https://www.virscan.org/
    - name: 漏洞查询  CVE
      sites:
        - name: 阿里云漏洞库
          description: 阿里云漏洞库
          url: https://avd.aliyun.com/nvd/list
        - name: tenable漏洞库(nessus)
          description: nessus
          url: https://www.tenable.com/cve/search
        - name: cve
          description: cve
          url: https://cve.mitre.org/cve/search_cve_list.html
        - name: nvd
          description: nvd
          url: https://nvd.nist.gov/vuln/search
        - name: accenture
          description: acc
          url: https://bugtraq.securityfocus.com/archive
        - name: php 漏洞查询
          description: php 漏洞查询
          url: https://bugs.php.net/

    - name: 安全资讯、技术学习
      sites:
        - name: 安全客
          description: 安全资讯平台
          url: https://www.anquanke.com/
        - name: freebuf
          description: 网络安全门户
          url: https://www.freebuf.com/
        - name: Seebug
          description: Paper - 安全技术精粹
          url: https://paper.seebug.org/category/web-security/
        - name: 安全牛
          description: 安全牛学习平台
          url: https://www.aqniu.com/
        - name: 红客
          description: 红客ctf
          url: https://www.hong.ke/news/ctf
        - name: 先知社区
          description: 先知社区
          url: https://xz.aliyun.com/
        - name: F12sec
          description: F12sec
          url: http://www.0dayhack.net/
        - name: 吾爱破解
          description: re
          url: https://www.52pojie.cn/
        - name: Sec-News
          description: 各种ctf writeup 收录了各种出题人的文章
          url: https://wiki.ioin.in/sort/ctf/page-1
    - name: Other
      sites:
        - name: zlib
          description: zlib 各种电子书pdf下载
          url: https://zlib.pro/
        - name: 字典
          description: 字典下载
          url: https://weakpass.com/
        - name: 命令安装
          description: 可以快速列出在不通平台安装所需命令
          url: https://command-not-found.com/
        - name: PHP static code analysis
          description: 静态规则匹配
          url: https://rules.sonarsource.com/php/
        


